### ISSUE TITLE
Set Up Testnet

### ISSUE THREAD

**Issue by troggy** [parsec-labs/parsec-node#12]
# Bounty 9: Set Up Testnet

## Scope:
- deploy slot ui
- create docs
- have a network that people can join and send transactions

## Deliverables:
- docs
- ui deployed

## ToDo:
- [x] deploy slot ui
- [x] create docs
- [x] 2 nodes running in sync with HTTPS
- [x] publicly available config to join the network
- [x] `x` blocks mined

----

Bounties: https://github.com/parsec-labs/PIPs/wiki/Bounties

**Comment by johannbarbie** [comment]
put the genesis file somewhere
